<?php
/**
* @file
* Users Forcontu
* Forcontu - Ejemplos de usuarios
*/
/**
* Implements hook_block_info().
*/
function users_forcontu_block_info() {
  // Bloque Ficha de usuario
  $blocks['user_data'] = array(
    'info' => t('User Data'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}
/**
* Implements hook_block_view().
*/
function users_forcontu_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'user_data':
      //necesitamos acceder al objeto $user del usuario actual
      global $user;
      $block['subject'] = t('User Data');
      if (user_is_logged_in()){
        if ($user->picture){
          //carga el objeto archivo de la imagen de usuario
          $picture_file = file_load($user->picture);
          //obtiene la URL final a partir de la URL en formato URI
          $picture_url = file_create_url($picture_file->uri);
        }
        $output = '<div class="user_block_registered">';
        if ($user->picture) {
          $output .= '<div id="image">' . l('<img src="' . $picture_url.'">',
          'user/'. $user->uid, array('html'=>TRUE)) . '</div>';
        }
        $output .= l($user->name, 'user/'. $user->uid);
        $output .= '</div>';
        $output .= '<div id="logout">'.l(t('Logout'),'user/logout').'</div>';
      }else{
        $output = '<div class="user_block_anonymous">';
        $output = '<p>Usted no ha iniciado <a href="/user/login"
        title="Iniciar Sesión">sesión</a> o no está <a href="/user/register"
        title="Registrarme">registrado</a><p>';
        $output .= '</div>';
      }
      $block['content'] = $output;
    break;
  }
  return $block;
}
/**
* Implements hook_form_alter.
*/
function users_forcontu_form_alter(&$form, &$form_state, $form_id) {
  switch($form_id){
    case 'user_register_form': //formulario de registro de usuario
      $form['firstname'] = array(
        '#type' => 'textfield',
        '#title' => t('First name'),
        '#description' => t('First name'),
        '#required' => 1,
        '#lenght' => 255,
      );
      $form['lastname'] = array(
        '#type' => 'textfield',
        '#title' => t('Last name'),
        '#description' => t('Last name'),
        '#required' => 1,
        '#lenght' => 255,
      );
      $form['web'] = array(
        '#type' => 'textfield',
        '#title' => 'Web',
        '#description' => t('User\'s web'),
        '#required' => 0,
        '#lenght' => 255,
      );
      break;
    case 'user_profile_form': //formulario de edición de usuario
      // Obtiene los datos del usuario.
      $uid = (int)$form['#user']->uid;
      $account = user_load($uid);
      $form['firstname'] = array(
        '#type' => 'textfield',
        '#title' => t('First name'),
        '#description' => t('First name'),
        '#required' => 1,
        '#lenght' => 255,
        '#default_value' => (($account->data['firstname']) ?
        $account->data['firstname'] : ''),
      );
      $form['lastname'] = array(
        '#type' => 'textfield',
        '#title' => t('Last name'),
        '#description' => t('Last name'),
        '#required' => 1,
        '#lenght' => 255,
        '#default_value' => (($account->data['lastname']) ?
        $account->data['lastname'] : ''),
      );
      $form['web'] = array(
        '#type' => 'textfield',
        '#title' => 'Web',
        '#description' => t('User web'),
        '#required' => 0,
        '#lenght' => 255,
        '#default_value' => (($account->data['web']) ? $account->data['web'] : ''),
      );
      break;     
  }
}
/**
* Implements hook_user_presave.
*/
function users_forcontu_user_presave(&$edit, $account, $category) {
  $edit['data'] = array(
    'firstname' => $edit['firstname'],
    'lastname' => $edit['lastname'],
    'web' => $edit['web'],
  );
}